io:
    output_dir: /home/laat/tmp/30s/GA9
    overwrite: True
max_workers: 36
source:
    wfs_dir        : /nfs/turbo/lsa-zspica/data/Halema/RAW/wfs/
    inventory_file : /nfs/turbo/lsa-zspica/work/laat/Halema/paper/inventory.xml
    channels_csv   : ./example/channels.csv
    starttime      : '2018-05-05 12:00'
    endtime        : '2018-05-27 16:00'
    # starttime      : '2018-05-12 00:00'
    # endtime        : '2018-05-12 12:00'
    sampling_rate  : 100.
preprocess:
    freqmin: 0.38
    freqmax: 6.24
window:
    length : 3600
    overlap: 0.0
    pad    : 0.05
test:
    time: '2018-05-12T02:00:00'
    # time: '2018-05-19T00:00:00'
uncertainty:
    n: 36
optimize:
    n          : 10000 # Number of Monte Carlo simulations
    filter     : [2, 0.3] # Butterworth order and normalized frequency
    obs_folder : /home/laat/tmp/30s/SSAM
    n_synth    : 2
    fnat_range: [0.3, 5]
moo:
    pop_size: 100
    n_offsprings: 100
    sbx:
        prob: 1
        eta: 1
    pm:
        prob: 1
        eta: 1
    n_gen: 40
    eliminate_duplicate: True
    n_partitions: 8 # Only for multiple-station
model:
    tau      : 30 # duration of simulation [s]
    max_freq : 6.25 # nyquist frequency [Hz] (Note: must be divisor of source.sampling_rate)
    xs       : 523800 # Cartesian easting [m]
    ys       : 63550 # Cartesian northing [m]
    zs       : 0 # Elevation [m]
    N        : 400 # number of mass impulses
    mu_g     : 1.e-5 # gas viscosity [Pa s]
    T        : 1100 # gas temperature [K]
    M        : 18.e-3 # molecular weight of gas (water vapor) [kg/mol]
    Rg       : 8.3145 # ideal gas constant [J/K/mol]
    Q        : [0.1, 2200] # mean gas flux [kg/s]
    R        : 150 # conduit radius [m]
    S        : null # conduit section [m^2]
    D        : [0.001, 10] # gas pocket thickness [m]
    L        : 250 # thickness of the cap [m]
    kappa    : 1.e-7 # permeability of the cap [m^2]
    phi      : 0.05e-2 # porosity of the cap [0-1]
    Pex      : 0.5e+7 # external pressure [Pa]
    Pex      : 101325 # external pressure [Pa]
    rho_s    : 2800 # density of the medium of propagation [kg/m^3]
    Qf       : [1, 150] # quality factor
post:
    n: 1.e+4 # Number of bootstrapping samples
    window: 1D # Moving window length
